version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .test.env
    depends_on:
      - pushgateway
    command: sh -c "./docker/test.sh"
    # tty: true
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
